name = "exclusive-content"
account_id = "706b3167d38200892ec8b6e44829a60d"
workers_dev = false
route = "https://webmonetization.org/api/exclusive-content/*"
main = "./src/index.ts"
compatibility_date = "2023-02-13"
