name: Tidy document
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'static/specification/index.html'
    branches:
      - gh-pages

jobs:
  tidy:
    name: Tidy up
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install tidy-html5
      - run: tidy -config static/tidyconfig.txt -o static/specification/index.html static/specification/index.html
      - uses: peter-evans/create-pull-request@v3
        with:
          title: 'Tidied up specification using tidy-html5'
          commit-message: 'chore(tidy): tidy up document'
          branch: html-tidy
